### PR TITLE
[JENKINS-32765] Expose the exploded plugin archive directory as a command line option

### PR DESCRIPTION
**Pull request by stephenc**
follow up to https://github.com/jenkinsci/jenkins/pull/2012

### CODE REVIEW

**Comment by stephenc** [comment]
@reviewbybees

**Comment by lordofthejars** [comment]
:bee: but I think that a unit test for this minimal logic would be also interesting to code it. I know it is fair simple but anyway it is always nice to have tests. :)

**Comment by andresrc** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees done

**Comment by stephenc** [comment]
@jenkinsci/code-reviewers

**Comment by daniel-beck** [comment]
It's not clear what the rationale is for a command line option, when a system property already exists. Wouldn't that conceivably result in confusion when specifying the latter which will be overridden by the former?

**Comment by stephenc** [comment]
@daniel-beck We want this to be at the same conceptual level as `--webroot=...` as if you have to set `--webroot` then you probably also have to set `--pluginroot=...`.

If you have the users needing to set one via a system property and the other via a CLI option, then you will have issues.

I couldn't see any other way to allow the executable-war main class inject the configuration for Jenkins to pick it up, other than by using a System Property to hand over to.

If we had a CLI only option then that would prevent somebody running in Bring-Your-Own-Servlet-Container mode from configuring the location (arguably we could look for servlet context parameters also in that case, but there are many reasons why running multiple Jenkins instances from the same servlet container is probably not going to work as well as you'd like), hence why exposing the system property makes the most sense and providing the CLI option is the preferred UX for users.

**Pull request merged**
